services:
  db:
    image: mysql:latest
    environment: 
      MYSQL_DATABASE: DB
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:3306:3306"
    expose:
      - "3306"
